# Generated by Django 5.2 on 2025-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=15)),
                ('seat_type', models.CharField(choices=[('Sleeper', 'Sleeper'), ('Seater', 'Seater')], max_length=15)),
                ('total_seats', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
