# Generated by Django 5.2 on 2025-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_schedule_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='travel_date',
            field=models.DateField(),
        ),
    ]
